# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\Widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(476, 417)
        self.layoutWidget = QtWidgets.QWidget(Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 421, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Age = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_Age.setObjectName("groupBox_Age")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_Age)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 391, 80))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.sliderSetAge = QtWidgets.QSlider(self.layoutWidget1)
        self.sliderSetAge.setMaximum(100)
        self.sliderSetAge.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSetAge.setObjectName("sliderSetAge")
        self.gridLayout.addWidget(self.sliderSetAge, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.editAgeInt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.editAgeInt.setObjectName("editAgeInt")
        self.gridLayout.addWidget(self.editAgeInt, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.editAgeStr = QtWidgets.QLineEdit(self.layoutWidget1)
        self.editAgeStr.setObjectName("editAgeStr")
        self.gridLayout.addWidget(self.editAgeStr, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_Age)
        self.groupBox_Name = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_Name.setObjectName("groupBox_Name")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_Name)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 391, 58))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.editNameInput = QtWidgets.QLineEdit(self.layoutWidget2)
        self.editNameInput.setObjectName("editNameInput")
        self.gridLayout_2.addWidget(self.editNameInput, 0, 1, 1, 1)
        self.btnSetName = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnSetName.setObjectName("btnSetName")
        self.gridLayout_2.addWidget(self.btnSetName, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.editNameHello = QtWidgets.QLineEdit(self.layoutWidget2)
        self.editNameHello.setObjectName("editNameHello")
        self.gridLayout_2.addWidget(self.editNameHello, 1, 1, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_Name)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnClose = QtWidgets.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/weld.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_2.addWidget(self.btnClose)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.groupBox_Age.setTitle(_translate("Widget", "年龄设置"))
        self.label_3.setText(_translate("Widget", "设置年龄(0~100)"))
        self.label.setText(_translate("Widget", "ageChanges(int)响应"))
        self.label_2.setText(_translate("Widget", "ageChanges(str)响应"))
        self.groupBox_Name.setTitle(_translate("Widget", "姓名设置"))
        self.label_4.setText(_translate("Widget", "输入姓名"))
        self.btnSetName.setText(_translate("Widget", "设置姓名"))
        self.label_5.setText(_translate("Widget", "nameChanged(str)响应"))
        self.btnClose.setText(_translate("Widget", "关闭"))

import res_rc
